{
 "title": "API Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "логи ошибок",
   "type": "logs",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{project=\"DataBaseManager\", level=\"ERROR\"}"
    }
   ]
  },
  {
   "title": "Логи",
   "type": "logs",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{project=\"DataBaseManager\"}"
    }
   ]
  },
  {
   "title": "Общее количество запросов по endpoint",
   "type": "gauge",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (path_template) (\n  count_over_time({project=\"DataBaseManager\"} | json | path_template!=\"\" [$__range])\n)",
     "legendFormat": "{{path_template}}"
    }
   ]
  },
  {
   "title": "Среднее время ответа по эндпоинтам за все время",
   "type": "gauge",
   "description": "Среднее время обработки запросов по эндпоинтам",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (path_template) (avg_over_time({project=\"DataBaseManager\"} | unwrap duration | __error__=\"\" [$__interval]))",
     "legendFormat": "{{path_template}}"
    }
   ]
  },
  {
   "title": "Среднее время ответа по эндпоинтам",
   "type": "timeseries",
   "description": "Среднее время обработки запросов по эндпоинтам",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (path_template) (avg_over_time({project=\"DataBaseManager\"} | unwrap duration | __error__=\"\" [$__interval]))",
     "legendFormat": "{{path_template}}"
    }
   ]
  },
  {
   "title": "Ошибки 4xx/5xx",
   "type": "timeseries",
   "description": "Распределение HTTP-статусов",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "sum by (status) (rate({project=\"DataBaseManager\"} | json | status=~\"[0-9]+\" | status >= 400 [$__interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}