name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.REMOTE_SSH_KEY }}

    - name: Copy files to remote server
      run: |
        # Создаем директорию на удаленном сервере
        ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'mkdir -p ~/app'
        
        # Копируем необходимые файлы
        scp -o StrictHostKeyChecking=no docker-compose.yaml ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:~/app/
        scp -o StrictHostKeyChecking=no -r config ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:~/app/
        scp -o StrictHostKeyChecking=no Makefile ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:~/app/

    - name: Deploy on remote server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          cd ~/app
          
          # Создаем Docker volumes если они еще не существуют
          docker volume create --name=grafana-data || true
          docker volume create --name=loki-data || true
          
          # Останавливаем существующие контейнеры, сохраняя volumes
          docker compose down --volumes=false || true
          
          # Устанавливаем правильные права на volumes
          docker run --rm -v grafana-data:/data busybox chown -R 472:472 /data
          docker run --rm -v loki-data:/data busybox chown -R 10001:10001 /data
          
          # Запускаем новые контейнеры
          docker compose up -d
          
          # Ждем, пока сервисы запустятся
          sleep 30
          
          # Проверяем статус контейнеров
          docker compose ps
          
          # Проверяем логи на наличие ошибок
          docker compose logs --tail=50
        EOF