name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Transfer files to remote server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        source: "."
        target: "/opt/${{ github.event.repository.name }}"
        strip_components: 0

    - name: Deploy on remote server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |
          cd /opt/${{ github.event.repository.name }}
          
          # Создаем необходимые директории для конфигов если их нет
          mkdir -p config/grafana/{datasources,plugins,dashboards}
          mkdir -p config/{loki,promtail}
          
          # Останавливаем существующие контейнеры
          docker compose down || true
          
          # Запускаем новые контейнеры
          docker compose up -d